version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "5000:80"
      - "8080:8080"
    environment:
      FLASK_PORT: 8000
      SINATRA_PORT: 4567
      SLIM_PORT: 8080
      NODE_PORT: 3000
      TZ: Asia/Tokyo
    volumes:
      - ./app/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/config/nginx/templates:/etc/nginx/templates:ro
      - ./app/html:/usr/share/nginx/html:ro
    depends_on:
      - flask
      - slim
      - sinatra
      - node
    command: >-
        webproc -c /etc/nginx/conf.d/default.conf -c /etc/nginx/nginx.conf -- /usr/sbin/nginx -g "daemon off;"

  flask:
    build:
      context: ./flask
    expose:
      - 8000
    volumes:
      - ./flask/src:/app/src
    environment:
      FLASK_ENV: ${FLASK_ENV:-development}
      FLASK_APP: app.py
#    command: flask run --host 0.0.0.0 --port 8000

  sinatra:
    build:
      context: ./sinatra
    expose:
      - 4567
    volumes:
      - ./sinatra/src:/app/src
    environment:
      APP_ENV: ${APP_ENV:-development}
#    command: bundle exec ruby src/app.rb -o 0.0.0.0 -p 4567

  slim:
    build:
      context: ./slim
    expose:
      - 8080
    environment:
      SLIM_MODE: development
    volumes:
      - ./slim/src:/app/src
#    command: php -S 0.0.0.0:8080 index.php

  node:
    build:
      context: ./node
    expose:
      - 3000
    volumes:
      - ./node/src:/app/src
#    command: node src/index.js
